# Generated by Django 4.2.4 on 2023-08-16 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_user_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='book_quantity can not be less than 1')])),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.order')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.shop')),
            ],
        ),
    ]
